### ISSUE TITLE
Better heading font

### ISSUE THREAD

**Issue by lukas-h** [lukas-h/material-theme#10]
Anyone knows a good one?

**Comment by GeorgeWL** [comment]
A sans-serif font like Raleway, Montserrat or Oswald does a good font-pairing with a the monospace font used.

Or maybe Poiret One or Comfortaa if you want to pair it with a display font. Or maybe even Chonburi

  I feel that the intentionally minimal style pairs better with these because they're also quite minimal.

**Comment by lukas-h** [comment]
Chonrubi Looks quite nice! Thanks a lot for your suggestions.

**Comment by GeorgeWL** [comment]
you're welcome :) I edited the css to get rid of the original header font and I'm going to use it on my gh-pages soon

**Comment by lukas-h** [comment]
You could create a pull request with your changes, if you want. Really appreciated, that people use my theme :smile:

**Comment by GeorgeWL** [comment]
well so far I only changed the inspect view, not got around to making the changes into for real...
