### ISSUE TITLE
Weird window behaviour and bullet point support

### ISSUE THREAD

**Issue by lf-araujo** [lukas-h/material-theme#14]
Dear Lukas,

Thanks for the excellent theme.
I found two bugs (or perhaps not) in your theme.

First, it does not seem to support bullet points. The code below does not work:

```markdown
- Create a directory in your dropbox folder (I name it mighty_make) and `cd` into it
- Download `mighty_make` with: `wget http://tiny.cc/mighty_test -O Makefile`
- Prepare the folder structure with `make prepare`
- Optional (for collaboration): Log into your dropbox account and share the directory with your collaborator
```
But the below works perfectly:

```markdown
1. Create a directory in your dropbox folder (I name it mighty_make) and `cd` into it
2. Download `mighty_make` with: `wget http://tiny.cc/mighty_test -O Makefile`
3. Prepare the folder structure with `make prepare`
4. Optional (for collaboration): Log into your dropbox account and share the directory with your collaborator
```

The second problem is how the theme is handling the width of the column. The theme looks better (the width is larger) in a tablet than in a fully maximized browser. The animated gif should give an idea of the problem:

![peek 24-10-2017 10-38](https://user-images.githubusercontent.com/10139950/31918503-bd84198c-b8a8-11e7-8343-ed0f06a270ef.gif)

Best

**Comment by lukas-h** [comment]
Sorry for not answering for a long time @lf-araujo
or a long time.

### column width

It is using the grid system from materializecss.com http://materializecss.com/grid.html - Maybe you want to adjust the CSS classes for the default layout 's content div:

```
<div class="row">
          <div class="col s12 m8 offset-m2 l6 offset-l3">
            {{ content }}
          </div>
        </div>
```
You could change the classes from `"col s12 m8 offset-m2 l6 offset-l3"` to `"col s12 m8 offset-m2 l8 offset-l2"`. That would be a quick fix. Otherwise you could try to edit the media queries in the materialize css file https://github.com/lukas-h/material-theme/tree/gh-pages/styles/mlz.

### bullet point support
Looks like, there is support for ordered lists `<ol></ol>`, but not for unordered lists `<ul></ul>`.
You could write some css into the main.css file.
For example like this:
```
ul li{
list-style-type: disc;
}
ol li{
list-style-type: decimal;
}
```
https://css-tricks.com/almanac/properties/l/list-style/

**Comment by lf-araujo** [comment]
Thank you!

**Comment by lf-araujo** [comment]
Thanks again for the answer.

The solution you pointed out, Lukas, introduces a new problem. The blog post list now has bullet points if I add the above code into main.css.

Here is how it looks:

![captura de tela de 2017-12-26 18-59-58](https://user-images.githubusercontent.com/10139950/34351227-6eb69494-ea6f-11e7-998a-26e5eddb2dfc.png)

Do you have any idea on how to circumvent this?

**Comment by lukas-h** [comment]
Is this issue still active? @lf-araujo
(Sorry for missing to answer)

**Comment by lf-araujo** [comment]
No it is not. Will close it. Thank you!
